### ISSUE TITLE
19 tests fail on Python 3.4 (Ubuntu 12.04)

### ISSUE THREAD

**Issue by andrewclegg** [yhat/ggplot#318]
I tried testing ggplot on 3.4 with a view to including it in https://github.com/andrewclegg/snake-charmer but got a whole load of failures. Not sure if you are even thinking about 3.4, but in case this is helpful, I've pasted them in below.

[Here](https://drive.google.com/file/d/0B1HztRme3ZjZSWViYlo1bUxlZGs/edit?usp=sharing) are the result images -- mostly looks like missing legends.

See [here](https://github.com/andrewclegg/snake-charmer/blob/53a5d626d9dfec6ea2f33a1881942d0ca8a5adc3/salt/roots/pillar/python34.sls) for a full list of installed packages with version numbers.

```
vagrant@charmed34:/srv/cache/src/ggplot$ nosetests-3.4 ggplot
.A variable was mapped to y.
    stat_bin sets the y value to the count of cases in each group.
    The mapping to y was ignored.
    If you want y to represent values in the data, use stat="identity".
stat_bin: binwidth defaulted to range/30.
    Use 'binwidth = x' to adjust this.
/usr/local/lib/python3.4/dist-packages/pandas/util/decorators.py:53: FutureWarning: rows is deprecated, use index instead
  warnings.warn(msg, FutureWarning)
EEE.'geom_line()' currenty does not support the mapping of size ('aes(size=<var>'), using size=4 as a replacement.
Use 'geom_line(size=x)' to set the size for the whole line.
E.E'geom_line()' currenty does not support the mapping of size ('aes(size=<var>'), using size=4 as a replacement.
Use 'geom_line(size=x)' to set the size for the whole line.
E'geom_line()' currenty does not support the mapping of size ('aes(size=<var>'), using size=4 as a replacement.
Use 'geom_line(size=x)' to set the size for the whole line.
E'geom_line()' currenty does not support the mapping of size ('aes(size=<var>'), using size=4 as a replacement.
Use 'geom_line(size=x)' to set the size for the whole line.
E.Estat_bin2d is still under construction.
The resulting plot lacks color to indicate the counts/density in each bin
and if grouping/facetting is used you get more bins than specified and
they vary in size between the groups.

see: https://github.com/yhat/ggplot/pull/266#issuecomment-41355513
     https://github.com/yhat/ggplot/issues/283
E..E..........................................EE......./srv/cache/src/ggplot/ggplot/ggplot.py:198: RuntimeWarning: Facetting is currently not supported with geom_bar. See
                    https://github.com/yhat/ggplot/issues/196 for more information
  warnings.warn(msg, RuntimeWarning)
..ESaving 11.0 x 8.0 in image.
Saving 11.0 x 8.0 in image.
Saving 11.0 x 8.0 in image.
Saving 11.0 x 8.0 in image.
Saving 22.0 x 16.0 in image.
Saving 22.0 x 16.0 in image.
Saving 1.0 x 8.0 in image.
Saving 11.0 x 1.0 in image.
Saving 11.0 x 8.0 in image.
..Saving 11.0 x 8.0 in image.
.Saving 11.0 x 8.0 in image.
Saving 300.0 x 8.0 in image.
Saving 11.0 x 300.0 in image.
Saving 11.0 x 8.0 in image.
.Saving 11.0 x 8.0 in image.
.Saving 11.0 x 8.0 in image.
.............E..EE.E...........E..................
======================================================================
ERROR: ggplot.tests.test_basic.test_geom_histogram
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 48, in test_geom_histogram
    assert_same_ggplot(gg + geom_histogram(), "geom_hist")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/geom_hist.png vs. /srv/cache/src/ggplot/result_images/test_basic/geom_hist-expected.png (RMS 86.98)

======================================================================
ERROR: ggplot.tests.test_basic.test_geom_point
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 57, in test_geom_point
    assert_same_ggplot(gg, "geom_point_vline")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/geom_point_vline.png vs. /srv/cache/src/ggplot/result_images/test_basic/geom_point_vline-expected.png (RMS 17.81)

======================================================================
ERROR: ggplot.tests.test_basic.test_geom_area
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 63, in test_geom_area
    assert_same_ggplot(gg + geom_area(), "geom_area")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/geom_area.png vs. /srv/cache/src/ggplot/result_images/test_basic/geom_area-expected.png (RMS 66.84)

======================================================================
ERROR: ggplot.tests.test_basic.test_geom_line
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 73, in test_geom_line
    assert_same_ggplot(p + geom_line(), "factor_geom_line")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/factor_geom_line.png vs. /srv/cache/src/ggplot/result_images/test_basic/factor_geom_line-expected.png (RMS 22.21)

======================================================================
ERROR: ggplot.tests.test_basic.test_factor_geom_point
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 91, in test_factor_geom_point
    assert_same_ggplot(p + geom_point(), "factor_geom_point")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/factor_geom_point.png vs. /srv/cache/src/ggplot/result_images/test_basic/factor_geom_point-expected.png (RMS 19.69)

======================================================================
ERROR: ggplot.tests.test_basic.test_factor_geom_point_line
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 96, in test_factor_geom_point_line
    assert_same_ggplot(p + geom_line() + geom_point(), "factor_geom_point_line")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/factor_geom_point_line.png vs. /srv/cache/src/ggplot/result_images/test_basic/factor_geom_point_line-expected.png (RMS 22.36)

======================================================================
ERROR: ggplot.tests.test_basic.test_factor_point_line_title_lab
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 103, in test_factor_point_line_title_lab
    assert_same_ggplot(p, "factor_complicated")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/factor_complicated.png vs. /srv/cache/src/ggplot/result_images/test_basic/factor_complicated-expected.png (RMS 23.14)

======================================================================
ERROR: ggplot.tests.test_basic.test_labs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 110, in test_labs
    assert_same_ggplot(p, "labs")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/labs.png vs. /srv/cache/src/ggplot/result_images/test_basic/labs-expected.png (RMS 22.97)

======================================================================
ERROR: ggplot.tests.test_basic.test_stats_smooth
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 122, in test_stats_smooth
    assert_same_ggplot(gg, "stat_smooth")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/stat_smooth.png vs. /srv/cache/src/ggplot/result_images/test_basic/stat_smooth-expected.png (RMS 19.04)

======================================================================
ERROR: ggplot.tests.test_basic.test_stats_bin2d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 132, in test_stats_bin2d
    assert_same_ggplot(gg + stat_bin2d(), "stat_bin2d")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/stat_bin2d.png vs. /srv/cache/src/ggplot/result_images/test_basic/stat_bin2d-expected.png (RMS 48.03)

======================================================================
ERROR: ggplot.tests.test_basic.test_facet_wrap2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_basic.py", line 151, in test_facet_wrap2
    assert_same_ggplot(p + geom_density(fill=True, alpha=0.3) + facet_wrap("variable"), "geom_density_facet")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_basic/geom_density_facet.png vs. /srv/cache/src/ggplot/result_images/test_basic/geom_density_facet-expected.png (RMS 21.40)

======================================================================
ERROR: ggplot.tests.test_geom_lines.test_geom_festival_of_lines
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_geom_lines.py", line 151, in test_geom_festival_of_lines
    assert_same_ggplot(gg, 'geom_festival_of_lines')
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_geom_lines/geom_festival_of_lines.png vs. /srv/cache/src/ggplot/result_images/test_geom_lines/geom_festival_of_lines-expected.png (RMS 36.27)

======================================================================
ERROR: ggplot.tests.test_geom_rect.test_geom_rect
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_geom_rect.py", line 29, in test_geom_rect
    assert_same_ggplot(p, 'geom_rect')
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_geom_rect/geom_rect.png vs. /srv/cache/src/ggplot/result_images/test_geom_rect/geom_rect-expected.png (RMS 48.72)

======================================================================
ERROR: ggplot.tests.test_ggplot_internals.test_different_markers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_ggplot_internals.py", line 99, in test_different_markers
    assert_same_ggplot(gg + geom_point(size=3000), "geom_point_marker")
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_ggplot_internals/geom_point_marker.png vs. /srv/cache/src/ggplot/result_images/test_ggplot_internals/geom_point_marker-expected.png (RMS 18.21)

======================================================================
ERROR: ggplot.tests.test_readme_examples.test_meat
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_readme_examples.py", line 29, in test_meat
    assert_same_ggplot(gg, 'ggplot_meat')
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_readme_examples/ggplot_meat.png vs. /srv/cache/src/ggplot/result_images/test_readme_examples/ggplot_meat-expected.png (RMS 40.62)

======================================================================
ERROR: ggplot.tests.test_readme_examples.test_geom_density_example
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_readme_examples.py", line 48, in test_geom_density_example
    assert_same_ggplot(gg, 'geom_density_example')
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_readme_examples/geom_density_example.png vs. /srv/cache/src/ggplot/result_images/test_readme_examples/geom_density_example-expected.png (RMS 19.38)

======================================================================
ERROR: ggplot.tests.test_readme_examples.test_density_with_fill
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/test_readme_examples.py", line 55, in test_density_with_fill
    assert_same_ggplot(gg, 'density_with_fill')
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 122, in curried
    return _assert_same_ggplot_image(*args, **kwargs)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 70, in _assert_same_ggplot_image
    return _assert_same_figure_images(fig, name, test_file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
ggplot.tests.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_readme_examples/density_with_fill.png vs. /srv/cache/src/ggplot/result_images/test_readme_examples/density_with_fill-expected.png (RMS 23.30)

======================================================================
ERROR: ggplot.tests.test_reverse.test_scale_reverse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 174, in decorated
    _assert_same_figure_images(figure, baseline, _file, tol=tol)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 112, in _assert_same_figure_images
    raise ImagesComparisonFailure(msg)
nose.proxy.ImagesComparisonFailure: images not close: /srv/cache/src/ggplot/result_images/test_reverse/scale_without_reverse.png vs. /srv/cache/src/ggplot/result_images/test_reverse/scale_without_reverse-expected.png (RMS 27.53)
-------------------- >> begin captured stdout << ---------------------
<ggplot: (-9223363297161176937)>
<ggplot: (-9223363297161176972)>
<ggplot: (-9223363297161335373)>
<ggplot: (-9223363297161358683)>

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: ggplot.tests.test_stat_function.test_stat_function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/cache/src/ggplot/ggplot/tests/__init__.py", line 168, in decorated
    func()
  File "/srv/cache/src/ggplot/ggplot/tests/test_stat_function.py", line 23, in test_stat_function
    stat_function(fun=np.cos,color="blue"))
  File "/srv/cache/src/ggplot/ggplot/stats/stat.py", line 61, in __radd__
    return gg + _geom
  File "/srv/cache/src/ggplot/ggplot/geoms/geom.py", line 158, in __radd__
    gg = deepcopy(gg)
  File "/usr/lib/python3.4/copy.py", line 166, in deepcopy
    y = copier(memo)
  File "/srv/cache/src/ggplot/ggplot/ggplot.py", line 130, in __deepcopy__
    result.__dict__[key] = deepcopy(self.__dict__[key], memo)
  File "/usr/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.4/copy.py", line 219, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.4/copy.py", line 300, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python3.4/copy.py", line 300, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.4/copy.py", line 170, in deepcopy
    rv = reductor(x)
  File "/usr/local/lib/python3.4/dist-packages/numpy/core/__init__.py", line 61, in _ufunc_reduce
    return _ufunc_reconstruct, (whichmodule(func, name), name)
  File "/usr/lib/python3.4/pickle.py", line 283, in whichmodule
    for module_name, module in sys.modules.items():
nose.proxy.RuntimeError: dictionary changed size during iteration
-------------------- >> begin captured stdout << ---------------------
<ggplot: (8739693399195)>

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 126 tests in 91.264s

FAILED (errors=19)

```

**Comment by glamp** [comment]
tests no longer relevant
