### ISSUE TITLE
facet_wrap works but faced_grid doesn't

### ISSUE THREAD

**Issue by chanansh** [yhat/ggplot#466]
This works:
```
ggplot(x, aes(x='fraction_missing', y = 'score', color='imputation')) + geom_line() +  facet_wrap('base_estimator','dataset')
```
But this fails:
```
ggplot(x, aes(x='fraction_missing', y = 'score', color='imputation')) + geom_line() +  facet_grid(x='base_estimator',y='dataset')

C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 220, in catch_format_error
    r = method(self, *args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 697, in __call__
    printer.pretty(obj)
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 383, in pretty
    return _default_pprint(obj, self, cycle)
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 503, in _default_pprint
    _repr_pprint(obj, p, cycle)
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 685, in _repr_pprint
    output = repr(obj)
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\ggplot\ggplot.py", line 111, in __repr__
    figure = self.draw()
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\ggplot\ggplot.py", line 247, in draw
    fontdict=dict(rotation=-90, verticalalignment="center", horizontalalignment='left')
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 617, in text
    t.update(kwargs)
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\text.py", line 244, in update
    self.set_bbox(bbox)  # depends on font properties
  File "C:\Users\XXX\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\text.py", line 516, in set_bbox
    **props)
TypeError: __init__() got multiple values for argument 'width'
```

**Comment by glamp** [comment]
fixed in 0.9.3
