### ISSUE TITLE
factor not working

### ISSUE THREAD

**Issue by choushishi** [yhat/ggplot#476]
Greetings. 

I can not get this simplest `geom_bar` example to work
```
from ggplot import *

print ggplot(mtcars, aes('factor(cyl)')) +  geom_bar()
```
The error I get is:

```
Traceback (most recent call last):
  File "/Users/Choushishi/Desktop/internship/titanic/test2.py", line 3, in <module>
    print ggplot(mtcars, aes('factor(cyl)')) +  geom_bar()
  File "/Users/Choushishi/anaconda/lib/python2.7/site-packages/ggplot/ggplot.py", line 66, in __init__
    self.data = _apply_transforms(data, self.aesthetics)
  File "/Users/Choushishi/anaconda/lib/python2.7/site-packages/ggplot/ggplot.py", line 550, in _apply_transforms
    env.add_outer_namespace({"factor":factor})
AttributeError: 'EvalEnvironment' object has no attribute 'add_outer_namespace'
```

On contrary, use`'cyl'` instead of `'factor(cyl)'` works:
```
from ggplot import *

print ggplot(mtcars, aes('cyl')) + geom_bar()
```

I can run other examples in yhat's blog just fine. So I am sure that it's the `factor` that is causing the problem. I am using newest anaconda and ggplot version 0.6.8

**Comment by choushishi** [comment]
The solution in this [post](https://github.com/yhat/ggplot/issues/457) works for me
