### ISSUE TITLE
Installation problems [windows]

### ISSUE THREAD

**Issue by jan-glx** [yhat/ggplot#483]
`pip install -U ggplot` failed for me with:

    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
    Rolling back uninstall of scipy
Running `conda install scipy` beforhand resolved the issue. You might want to add this to `Note: Conda users...just use pip`.

And great work, @glamp, the last months! :sunglasses:

**Comment by glamp** [comment]
Thanks. I think what we really need is a conda repo 😄

**Comment by bjpcjp** [comment]
running `conda install scipy` solved it for me too. Nice catch.

**Comment by hoechenberger** [comment]
I simply installed `brewer2mpl` via pip, and then did a `pip install --no-deps -U ggplot` to ignore all `ggplot` dependencies during install. No need to mess up your existing Anaconda installation :)

**Comment by neokril** [comment]
I follow installation instruction. Got this error on windows 7 x64:

```
C:\>pip install -U ggplot
Collecting ggplot
  Using cached ggplot-0.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\TEMP\pip-build-0qzabcc4\ggplot\setup.py", line 3, in <module>
        from ggplot.__init__ import __version__
      File "C:\TEMP\pip-build-0qzabcc4\ggplot\ggplot\__init__.py", line 16, in <module>
        _set_mpl_backend()
      File "C:\TEMP\pip-build-0qzabcc4\ggplot\ggplot\__init__.py", line 9, in _set_mpl_backend
        import matplotlib as mpl
    ImportError: No module named 'matplotlib'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\TEMP\pip-build-0qzabcc4\ggplot\
```
