### ISSUE TITLE
setup.py depends on install_requires

### ISSUE THREAD

**Issue by daradib** [yhat/ggplot#485]
@glamp In 5d2f1b2 (0.9.1), `setup.py` was simplified to import ggplot to get the package version. Unfortunately, `install_requires` aren't installed yet when running `setup.py`, so this breaks installation with `pip` and `setup.py`.

    $ pip install ggplot
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-M9YYS3/ggplot/setup.py", line 3, in <module>
            from ggplot.__init__ import __version__
          File "ggplot/__init__.py", line 34, in <module>
            from .scales.scale_color_brewer import scale_color_brewer
          File "ggplot/scales/scale_color_brewer.py", line 5, in <module>
            import brewer2mpl
        ImportError: No module named brewer2mpl

I would suggest using `pkg_resources` or a separate `version.py` file, as [discussed on StackOverflow](http://stackoverflow.com/a/2073599).

**Comment by glamp** [comment]
thanks @daradib fixed in 20f7cac7315ecfde3cdea560f26bcfdb710ca492
