### ISSUE TITLE
x-axis dates not formatting correctly for 'how it works' tutorial

### ISSUE THREAD

**Issue by rforgione** [yhat/ggplot#508]
Hey all -- I'm having some issues with the 'how it works' tutorial. x-axis dates are formatting incorrectly:

<img width="845" alt="screen shot 2016-07-22 at 12 12 30 am" src="https://cloud.githubusercontent.com/assets/5572997/17046444/7a12ca2a-4fa1-11e6-9c3f-6eaed4485a09.png">

Running 0.10.4 on El Capitan

**Comment by glamp** [comment]
Hey @rforgione, try using the [new tutorials instead](http://yhat.github.io/ggplot/docs.html). To format the x-axis labels for the dates, try this for now:

```
ggplot(meat, aes(x='date', y='beef')) + geom_point() + scale_x_date(labels='%Y')
```
![image](https://cloud.githubusercontent.com/assets/1409333/17058409/570da214-4fee-11e6-9f89-b49482e541b4.png)

We'll have to do some work on making the default scales beter.

**Comment by rforgione** [comment]
@glamp I'd love to contribute in any way that I can. If you wouldn't mind pointing me in the right direction I'd be happy to take a stab at this.

**Comment by pchtsp** [comment]
Not sure if this is the correct place (or if I should open another issue) but the examples with `geom_line()` do not work for `scale_x_date`. It does work with `geom_point` though. Which is really weird. It complains about limits: apparently the dates are taken as very big integer values and do not enter in the graph. I have tried to search where the conversion error happens but I'm not sure how to debug the ggplot-matplotlib library.

I'm using: 

    Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
    [GCC 5.4.0 20160609] on Ubuntu 16.04 64 bit

    ggplot==0.11.5
    matplotlib==2.1.1

For example if I try the following:

    ggplot(meat, aes('date', 'beef')) + \
    geom_line() + \
    scale_x_date(labels="%Y-%m-%d")

I get the following error and the attached image:

    Traceback (most recent call last):
      File "<input>", line 3, in <module>
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/ggplot/ggplot.py", line 116, in __repr__
        self.make()
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/ggplot/ggplot.py", line 641, in make
        self.apply_axis_labels()
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/ggplot/ggplot.py", line 231, in apply_axis_labels
        labels.append(self.xtick_formatter(label_text))
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 542, in __call__
        dt = num2date(x, self.tz)
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 445, in num2date
        return _from_ordinalf(x, tz)
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 260, in _from_ordinalf
        dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
    OverflowError: signed integer is less than minimum

![figure_1](https://user-images.githubusercontent.com/5459187/35223825-12b7cfa4-ff83-11e7-9dc6-ef7abbda08b6.png)

**Comment by pchtsp** [comment]
Not sure if this is the correct place (or if I should open another issue) but the examples with `geom_line()` do not work for `scale_x_date`. It does work with `geom_point` though. Which is really weird. It complains about limits: apparently the dates are taken as very big integer values and do not enter in the graph. I have tried to search where the conversion error happens but I'm not sure how to debug the ggplot-matplotlib library.

I'm using: 

    Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
    [GCC 5.4.0 20160609] on Ubuntu 16.04 64 bit

    ggplot==0.11.5
    matplotlib==2.1.1

For example if I try the following:

    ggplot(meat, aes('date', 'beef')) + \
    geom_line() + \
    scale_x_date(labels="%Y-%m-%d")

I get the following error and the attached image:

    Traceback (most recent call last):
      File "<input>", line 3, in <module>
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/ggplot/ggplot.py", line 116, in __repr__
        self.make()
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/ggplot/ggplot.py", line 641, in make
        self.apply_axis_labels()
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/ggplot/ggplot.py", line 231, in apply_axis_labels
        labels.append(self.xtick_formatter(label_text))
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 542, in __call__
        dt = num2date(x, self.tz)
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 445, in num2date
        return _from_ordinalf(x, tz)
      File "/home/pchtsp/Documents/projects/OPTIMA/python/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 260, in _from_ordinalf
        dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
    OverflowError: signed integer is less than minimum

![figure_1](https://user-images.githubusercontent.com/5459187/35223825-12b7cfa4-ff83-11e7-9dc6-ef7abbda08b6.png)
