### ISSUE TITLE
ggplot.py line 134: AttributeError: 'geom_line' object has no attribute 'values'

### ISSUE THREAD

**Issue by b-filip** [yhat/ggplot#540]
I am trying to do basic hello world examples from the documentation, and they don't work:

```
from ggplot import ggplot, geom_line, aes, mtcars
ggplot(data=mtcars, aesthetics=aes('wt', 'mpg', 'qsec') + geom_line())
```

```
python ../mtcars.py
Traceback (most recent call last):
  File "../mtcars.py", line 2, in <module>
    ggplot(mtcars, aes('wt', 'mpg', 'qsec') + geom_line())
  File "/home/shibbiry/.virtualenvs/ggplot_bug/lib/python3.5/site-packages/ggplot/ggplot.py", line 55, in __init__
    self._handle_index()
  File "/home/shibbiry/.virtualenvs/ggplot_bug/lib/python3.5/site-packages/ggplot/ggplot.py", line 134, in _handle_index
    if '__index__' in self._aes.values():
AttributeError: 'geom_line' object has no attribute 'values'
```

Here is all the relevant info which should help you reproduce the bug. I literally created a new virtualenv and installed all required packages there to report this:

``` 
$ mkvirtualenv ggplot_bug # automatically invokes activate script
$ pip install ggplot
$ pip freeze
brewer2mpl==1.4.1
cycler==0.10.0
ggplot==0.11.2
matplotlib==1.5.2
numpy==1.11.1
pandas==0.18.1
patsy==0.4.1
pyparsing==2.1.8
python-dateutil==2.5.3
pytz==2016.6.1
scipy==0.18.0
six==1.10.0
statsmodels==0.6.1
$ python ../mtcars.py
Traceback (most recent call last):
  File "../mtcars.py", line 2, in <module>
    ggplot(data=mtcars, aesthetics=aes('wt', 'mpg', 'qsec') + geom_line())
  File "/home/shibbiry/.virtualenvs/ggplot_bug/lib/python3.5/site-packages/ggplot/ggplot.py", line 55, in __init__
    self._handle_index()
  File "/home/shibbiry/.virtualenvs/ggplot_bug/lib/python3.5/site-packages/ggplot/ggplot.py", line 134, in _handle_index
    if '__index__' in self._aes.values():
AttributeError: 'geom_line' object has no attribute 'values'
```

I haven't really tried to figure out anything on my own, but purely from the error messages maybe pandas changed API of dataframe?

**Comment by b-filip** [comment]
Nevermind, I've just looked at another [docs page](http://ggplot.yhathq.com/docs/geom_line.html) and figured out that you must add `geom_line()` not to aesthetics but to the object returned by ggplot.
